In [1]:
# Question 1
x = 2
y = 3
del x

In [2]:
# Question 2
# x ** 2

# OUTPUT:
# NameError: name 'x' is not defined

In [3]:
# Question 3
import math
x = 10
y = 3
u = x + y
v = x * y
w = x / y
z = math.sin(x)
r = 8 * math.sin(x)
s = 5 * math.sin(v)
p = x ** y

In [4]:
# Question 4
# %whos

In [5]:
# Question 5
S = '123'
N = float(S)
print(type(S), type(N))

<class 'str'> <class 'float'>


In [6]:
# Question 6
s1 = 'HELLO'
s2 = 'hello'
print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

False
True
True


In [7]:
# Question 7
s3 = 'Engineering'
s4 = 'Book'
print(f'The word "{s3}" has {len(s3)} letters')
print(f'The word "{s4}" has {len(s4)} letters')

The word "Engineering" has 11 letters
The word "Book" has 4 letters


In [8]:
# Question 8
"Python" in "Python is great!"

True

In [9]:
# Question 9
"Python is great!"[-6:]

'great!'

In [10]:
# Question 10
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)
list_a

[1, 2, 8, 9, 15, 4]

In [11]:
# Question 11
list_a.sort()
list_a

[1, 2, 4, 8, 9, 15]

In [12]:
# Question 12
print(list('Python is great!'))

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'g', 'r', 'e', 'a', 't', '!']


In [13]:
# Question 13
tuple_a = ("One", 1)

In [14]:
# Question 14
tuple_a[1]

1

In [15]:
# Question 15
set((2, 3, 2, 3, 1, 2, 5))

{1, 2, 3, 5}

In [16]:
# Question 16
set_a = set((2,3,2))
set_b = set((3,1,2))
print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))
print(set_b.difference(set_a))


{1, 2, 3}
{2, 3}
set()
{1}


In [17]:
# Question 17
dict_a = {"A":"a", "B":"b", "C":"c"}
dict_a.keys()

dict_keys(['A', 'B', 'C'])

In [18]:
# Question 18
print("B" in dict_a)
print("B" in dict_a.keys())

True
True


In [19]:
# Question 19
import numpy as np
x = np.array([1, 4, 3, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])
print(x + y)
print(x * y)
print(x / y)
print(np.sin(x))
print(8 * np.sin(x))
print(5 * np.sin(x*y))
print(x ** y)


[ 3  7  7  3 11  7]
[ 2 12 12  2 18 12]
[0.5        1.33333333 0.75       2.         4.5        1.33333333]
[ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ]
[ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996]
[ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459]
[ 1 64 81  2 81 64]


In [20]:
# Question 20
np.linspace(-10, 10, 100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [21]:
# Question 21
array_a = np.array([-1, 0, 1, 2, 0, 3])
array_a[array_a > 0]

array([1, 2, 3])

In [22]:
# Question 22
np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]]).transpose()

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

In [23]:
# Question 23
t = np.zeros((2,4))

In [24]:
# Question 24
t[:, 1] = np.ones(2)
t

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [25]:
# Question 25
# %reset