In [37]:
from math import pi, acos
import numpy as np
from numpy.linalg import norm, matrix_rank

In [38]:
# Question 3a
def my_is_orthogonal(v1,v2,tol):
    temp = np.dot(v1.T,v2) #--> This is a square matrix of order 1.
    theta = acos(temp[0,0]/(norm(v1)*norm(v2)))
    return int(abs(pi/2-theta)<tol)

In [39]:
a = np.array([[1], [0.001]])
b = np.array([[0.001], [1]])

print(my_is_orthogonal(a, b, 0.01))
print(my_is_orthogonal(a, b, 0.001))

1
0


In [40]:
a = np.array([[1], [0.001]])
b = np.array([[1], [1]])
my_is_orthogonal(a,b, 0.01)

0

In [41]:
a = np.array([[1], [1]])
b = np.array([[-1], [1]])
my_is_orthogonal(a,b, 1e-10)

1

In [42]:
# Question 3b
def my_is_similar(s1,s2,tol):
    v1 = np.zeros(26)
    v2 = np.zeros(26)
    alpha = 'abcdefghijklmnopqrstuvwxyz'
    for i in range(26):
        v1[i] = s1.count(alpha[i])
        v2[i] = s2.count(alpha[i])
    theta = acos(np.dot(v1,v2)/(norm(v1)*norm(v2)))
    return int(abs(theta) < tol)   

In [43]:
s1 = 'numericalcomputing'
s2 = 'fundamentalsofcomputingandprogramming'

print(my_is_similar(s1,s2,pi))

1


In [44]:
s1 = 'acegikmoqsuwy'
s2 = 'bdfhjlnprtvxz'

print(my_is_similar(s1,s2,pi/2))

0


In [45]:
# Question 4
def my_make_lin_ind(A):
    m,n = A.shape
    B = np.zeros((m,1))
    B[:,0] = A[:,0]
    r = 1
    for i in range(1,n):
        x = np.array([[j] for j in A[:,i]])
        temp = np.concatenate((B, x),axis=1)
        if matrix_rank(temp) == r+1:
            B = temp
            r += 1
    return B

In [46]:
A = np.array([[12,24,0,11,-24,18,15],\
              [19,38,0,10,-31,25,9], \
              [1, 2, 0,21,-5, 3, 20],\
              [6, 12,0,13,-10,8, 5], \
              [22,44,0,2, -12,17,23]])

print(my_make_lin_ind(A))

[[ 12.  11. -24.  15.]
 [ 19.  10. -31.   9.]
 [  1.  21.  -5.  20.]
 [  6.  13. -10.   5.]
 [ 22.   2. -12.  23.]]


In [47]:
# Question 12
# Note: The solution is not unique and depends on how x and y are chosen.
# Here I have just shared them equally.

def my_flow_calculator(S,d):
    x = y = S[0,1] / 2
    z = S[0,0]
    f = [z, d[0,2], -(z - d[0,2]- d[0,3]), x, y, x-d[0,0], y-d[0,1]]
    f[5] -= f[2]
    return [[j] for j in f]

In [48]:
s = np.array([[10, 10]])
d = np.array([[4, 4, 4, 4, 4]])

my_flow_calculator(s,d)

[[10], [4], [-2], [5.0], [5.0], [3.0], [1.0]]

In [49]:
s = np.array([[10, 10]])
d = np.array([[3, 4, 5, 4, 4]])

my_flow_calculator(s,d)

[[10], [5], [-1], [5.0], [5.0], [3.0], [1.0]]