In [1]:
import numpy as np
import math

In [2]:
# Question 1
y = 0
for i in range(1000):
    for j in range(1000):
        if i == j:
            y += 1

print(y)
# y will be 1000 after the completion of loops.

1000


In [3]:
# Question 2
def my_max(x):
    out = x[0]
    for i in x:
        if i > out:
            out = i
    return out

print(my_max([11, 32, 45, 41, 25]))
print(my_max(range(7)))

45
6


In [4]:
# Question 3
def my_n_max(x, n):
    out = []
    for i in range(n):
        out.append(max(x))
        x.remove(out[i])
    return out

print(my_n_max([11, 32, 45, 41, 25], 2))
print(my_n_max([7, 9, 10, 5, 8, 3, 4, 6, 2, 1], 3))


[45, 41]
[10, 9, 8]


In [5]:
# Question 4
def my_trig_odd_even(m):
    nrow , ncol = np.shape(m)
    out = np.zeros((nrow, ncol))
    for i in range(nrow):
        for j in range(ncol):
            if m[i, j] % 2 == 0:
                out[i, j] = math.sin(m[i, j])
            else:
                out[i, j] = math.cos(m[i, j])
    return out

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_trig_odd_even(x))

[[ 0.54030231  0.90929743 -0.9899925 ]
 [-0.7568025   0.28366219 -0.2794155 ]
 [ 0.75390225  0.98935825 -0.91113026]]


In [6]:
# Question 5
def my_mat_mult(p, q):
    nrow_p, ncol_p = np.shape(p)
    nrow_q, ncol_q = np.shape(q)
    out = np.zeros((nrow_p, ncol_q))
    for i in range(nrow_p):
        for j in range(ncol_q):
            for k in range(ncol_p):
                out[i, j] += p[i, k] * q[k, j]
    return out

In [7]:
r = np.ones((3, 3))
print(my_mat_mult(r, r))
p = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
q = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(my_mat_mult(p, q))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[30. 30. 30.]
 [70. 70. 70.]]


In [8]:
# Question 6
def my_saving_plan(p0, i, goal):
    years = 0
    while p0 < goal:
        p0 += p0 * i
        years += 1
    return years

print(my_saving_plan(1000, 0.05, 2000))
print(my_saving_plan(1000, 0.07, 2000))
print(my_saving_plan(500, 0.07, 2000))

15
11
21


In [9]:
# Question 7
def my_find(m):
    out = [i for i in range(len(m)) if m[i] == 1]
    return out

print(my_find([1, 0, 1, 1, 0]))

[0, 2, 3]


In [10]:
# Question 8

from random import choice

def my_monopoly_dice():
    d1 = d2 = out = 0
    while d1 == d2:
        d1 = choice(range(1,7))
        d2 = choice(range(1,7))
        out += (d1 + d2)
    return out

In [30]:
my_monopoly_dice()

25

In [11]:
# Question 9
def my_is_prime(n):
    if n == 1:
        return 0
    if n == 2 or n == 3:
        return 1
    if n % 2 == 0 or n % 3 == 0:
        return 0
    for i in range(5, int(math.sqrt(n)) + 1, 6):
        if n % i == 0 or n % (i + 2) == 0:
            return 0
    return 1

In [12]:
my_is_prime(1000000007)

1

In [13]:
# Question 10
def my_n_primes(n):
    if n == 1:
        return [2]
    else:
        out = [2,3]
        primes = 2
        i = 5
        while primes < n:
            if my_is_prime(i):
                out.append(i)
                primes += 1
            i += 2
            if my_is_prime(i):
                out.append(i)
                primes += 1
            i += 4
        if primes == n+1:
            out.pop()
        return out

In [14]:
print(my_n_primes(25))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [15]:
# Question 11
def my_n_fib_primes(n):
    fib = [1, 1, 2]
    out = []
    len_out = 0
    while len_out <= n:
        if my_is_prime(fib[-1]):
            out.append(fib[-1])
            len_out += 1
        fib[0] = fib[1]
        fib[1] = fib[2]
        fib[2] = fib[0] + fib[1]
    return out


In [16]:
print(my_n_fib_primes(10))

[2, 3, 5, 13, 89, 233, 1597, 28657, 514229, 433494437, 2971215073]


In [17]:
# Question 12
def my_trig_even_odd(M):
    nrow, ncol = np.shape(M)
    out = np.zeros((nrow, ncol))
    for i in range(nrow):
        for j in range(ncol):
            if M[i, j] % 2 == 0:
                out[i, j] = math.cos(math.pi/M[i, j])
            else:
                out[i, j] = math.sin(math.pi/M[i, j])
    return out

In [18]:
m = np.array([[3, 4], [6, 7]])
print(my_trig_even_odd(m))

[[0.8660254  0.70710678]
 [0.8660254  0.43388374]]


In [19]:
# Question 13
def my_connectivity_mat_2_dict(c, names):
    node = {}
    for i in range(len(names)):
        temp = []
        for j in range(len(names)):
            if c[i, j] == 1:
                temp.append(j+1)
        node[names[i]] = temp
    return node

c = np.array([[0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1], [1, 1, 1, 0]])
names = ["Los Angeles", "New York", "Miami", "Dallas"]
print(my_connectivity_mat_2_dict(c, names))

{'Los Angeles': [2, 4], 'New York': [1, 4], 'Miami': [4], 'Dallas': [1, 2, 3]}


In [20]:
# Question 14
words = ["test", "data", "analyze"]
cap_words = [i.upper() for i in words]
print(cap_words)

['TEST', 'DATA', 'ANALYZE']
