In [1]:
import numpy as np
import math

In [2]:
# Question 1
def my_tip_calc(bill, party):
    tips = 0
    if party < 6:
        tips = bill * 0.15
    elif party < 8:
        tips = bill * 0.18
    elif party < 11:
        tips = bill * 0.20
    else:
        tips = bill * 0.25
    return tips

print(my_tip_calc(109.29,3))
print(my_tip_calc(109.29,7))
print(my_tip_calc(109.29,9))
print(my_tip_calc(109.29,12))

16.3935
19.6722
21.858000000000004
27.3225


In [3]:
# Question 2
def my_mult_operation(a,b,operation):
    out = 0
    if operation == 'plus':
        out = a + b
    elif operation == 'minus':
        out = a - b
    elif operation == 'mult':
        out = a * b
    elif operation == 'div':
        out = a / b
    elif operation == 'pow':
        out = a ** b
    return out

In [4]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

print(my_mult_operation(x,y,'plus'))
print(my_mult_operation(x,y,'minus'))
print(my_mult_operation(x,y,'mult'))
print(my_mult_operation(x,y,'div'))
print(my_mult_operation(x,y,'pow'))

[3 5 7 9]
[-1 -1 -1 -1]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]
[   1    8   81 1024]


In [5]:
# Question 3
def my_inside_triangle(x,y):
    position = ""
    if 0<x<1 and 0<y<1 and x+y<1:
        position = "inside"
    elif x==0 or y==0 or x+y==1:
        position = "border"
    else:
        position = "outside"
    return position

print(my_inside_triangle(.5,.5))
print(my_inside_triangle(.25,.25))
print(my_inside_triangle(5,5))



border
inside
outside


In [6]:
# Question 4
def my_make_size10(x):
    size10 = []
    if len(x) > 10:
        size10 = x[0:10]
    else:
        size10 = list(x) + list(np.zeros(10 - len(x)))
    return size10 

print(my_make_size10(np.arange(1,3)))
print(my_make_size10(np.arange(1,15)))
print(my_make_size10([3,6,13,4]))

[1, 2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[ 1  2  3  4  5  6  7  8  9 10]
[3, 6, 13, 4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [7]:
# Question 5
def my_make_size10_2(x):
    out = list(x)
    for i in range(10 - len(x)):
        out.insert(len(out), 0)
    return out[:10]

In [8]:
print(my_make_size10_2(np.arange(1, 3)))
print(my_make_size10_2(np.arange(1,15)))

[1, 2, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
# Question 6
def my_letter_grader(percent):
    percent_dict = {97:"A+", 93:"A", 90:"A-", 87:"B+", 83:"B", 80:"B-",\
                     77:"C+", 73:"C", 70:"C-", 67:"D+", 63:"D", 60:"D-", 0:"F"}
    grade = ""
    for i in percent_dict:
        if percent >= i:
            grade = percent_dict[i]
            break
    return grade

print(my_letter_grader(97))
print(my_letter_grader(84))

A+
B


In [10]:
# Question 7
def my_nuke_alarm(s1, s2, s3):
    response = "normal"
    if abs(s2 -s1)>10 or abs(s3-s2)>10 or abs(s3-s1)>10:
        response = "alarm!"
    return response

print(my_nuke_alarm(94,96,90))
print(my_nuke_alarm(94,96,80))
print(my_nuke_alarm(100,96,90))

normal
alarm!
normal


In [11]:
# Question 8
def my_n_roots(a, b, c):
    n_roots = 0
    r = []
    disc = b**2 - 4*a*c
    if disc == 0:
        n_roots = 1
        r += [-b / (2*a)]
    elif disc > 0:
        n_roots = 2
        r += [(-b+math.sqrt(disc))/(2*a), (-b-math.sqrt(disc))/(2*a)]
    else:
        n_roots = -2
        z1 = complex(-b / (2*a), (math.sqrt(-disc))/(2*a))
        z2 = complex(-b / (2*a), -(math.sqrt(-disc))/(2*a))
        r += [z1, z2]
    return n_roots, r

In [12]:
n_roots, r = my_n_roots(1, 0, -9)
print(n_roots, r)

2 [3.0, -3.0]


In [13]:
n_roots, r = my_n_roots(3, 4, 5)
print(n_roots, r)

-2 [(-0.6666666666666666+1.1055415967851332j), (-0.6666666666666666-1.1055415967851332j)]


In [14]:
n_roots, r = my_n_roots(2, 4, 2)
print(n_roots, r)

1 [-1.0]


In [15]:
# Question 9
def my_split_function(f,g,a,b,x):
    if x<=a:
        return f(x)
    elif x>=b:
        return g(x)
    else:
        return 0
    
print(my_split_function(np.exp,np.sin,2,4,1))
print(my_split_function(np.exp,np.sin,2,4,3))
print(my_split_function(np.exp,np.sin,2,4,5))

2.718281828459045
0
-0.9589242746631385
