In [10]:
import math
import numpy as np

In [11]:
# Question 3
from numpy.linalg import norm
from math import acos

def my_is_similar(s1,s2,tol):
    v1 = np.zeros(26)
    v2 = np.zeros(26)
    alpha = 'abcdefghijklmnopqrstuvwxyz'
    for i in range(26):
        v1[i] = s1.count(alpha[i])
        v2[i] = s2.count(alpha[i])
    theta = acos(np.dot(v1,v2)/(norm(v1)*norm(v2)))
    return abs(theta) < tol   

In [12]:
s1 = 'numericalcomputing'
s2 = 'fundamentalsofcomputingandprogramming'

print(my_is_similar(s1,s2,math.pi/2))

True


In [13]:
s1 = 'acegikmoqsuwy'
s2 = 'bdfhjlnprtvxz'

print(my_is_similar(s1,s2,math.pi/2))

False


In [14]:
# Question 4
from numpy.linalg import matrix_rank
def my_make_lin_ind(A):
    m,n = A.shape
    B = np.zeros((m,1))
    B[:,0] = A[:,0]
    r = 1
    for i in range(1,n):
        x = np.array([[j] for j in A[:,i]])
        temp = np.concatenate((B, x),axis=1)
        if matrix_rank(temp) == r+1:
            B = temp
            r += 1
    
    return B

In [15]:
A = np.array([[12,24,0,11,-24,18,15],\
              [19,38,0,10,-31,25,9], \
              [1, 2, 0,21,-5, 3, 20],\
              [6, 12,0,13,-10,8, 5], \
              [22,44,0,2, -12,17,23]])

print(my_make_lin_ind(A))

[[ 12.  11. -24.  15.]
 [ 19.  10. -31.   9.]
 [  1.  21.  -5.  20.]
 [  6.  13. -10.   5.]
 [ 22.   2. -12.  23.]]


In [16]:
# Question 12
# Note: The solution is not unique and depends on how x and y are chosen.
# Here I have just shared them equally.

def my_flow_calculator(S,d):
    x = y = S[0,1] / 2
    z = S[0,0]
    f = [z, d[0,2], -(z - d[0,2]- d[0,3]), x, y, x-d[0,0], y-d[0,1]]
    f[5] -= f[2]
    return [[j] for j in f]

In [17]:
s = np.array([[10, 10]])
d = np.array([[4, 4, 4, 4, 4]])

my_flow_calculator(s,d)

[[10], [4], [-2], [5.0], [5.0], [3.0], [1.0]]

In [18]:
s = np.array([[10, 10]])
d = np.array([[3, 4, 5, 4, 4]])

my_flow_calculator(s,d)

[[10], [5], [-1], [5.0], [5.0], [3.0], [1.0]]