In [1]:
import numpy as np
import math

In [2]:
# Question 1
def my_sinh(x):
    return (np.exp(x) - np.exp(-x)) / 2

In [3]:
print(my_sinh(0))
print(my_sinh(1))
print(my_sinh(2))

0.0
1.1752011936438014
3.626860407847019


In [4]:
# Question 2
def my_checker_board(n):
    res = np.ones((n, n))
    for i in range(n):
        for j in range(n):
            if not (i + j) % 2 == 0:
                res[i, j] = 0
    return res

In [5]:
my_checker_board(1)

array([[1.]])

In [6]:
my_checker_board(2)

array([[1., 0.],
       [0., 1.]])

In [7]:
my_checker_board(3)

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [8]:
my_checker_board(5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

In [9]:
# Question 3
def my_triangle(b, h):
    return b * h / 2

In [10]:
print(my_triangle(1, 1))
print(my_triangle(2, 1))
print(my_triangle(12, 5))

0.5
1.0
30.0


In [11]:
# Question 4
def my_split_matrix(m):
    ncol = m.shape[1]
    num = 0
    if ncol % 2 == 0:
        num = ncol // 2
    else:
        num = (ncol // 2) + 1
    m1 = m[:,np.arange(0,num)]
    m2 = m[:,np.arange(num,ncol)]
    return [m1, m2]



In [12]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m1, m2 = my_split_matrix(m)
print(f"{m1} \n {m2}")

[[1 2]
 [4 5]
 [7 8]] 
 [[3]
 [6]
 [9]]


In [13]:
m = np.ones((5, 5))
m1, m2 = my_split_matrix(m)
print(f"{m1} \n {m2}")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
# Question 5
def my_cylinder(r,h):
    s = 2 * np.pi * r * (r + h)
    v = np.pi * r **2 * h
    return [s, v]

print(my_cylinder(1, 5))
print(my_cylinder(2, 4))

[37.69911184307752, 15.707963267948966]
[75.39822368615503, 50.26548245743669]


In [15]:
# Question 6
def my_n_odds(a):
    return len(a[a % 2 ==1])

print(my_n_odds(np.arange(100)))
print(my_n_odds(np.arange(2, 100, 2)))

50
0


In [16]:
# Question 7
def my_twos(m,n):
    temp = np.ones((m, n))
    return (temp * 2)

print(my_twos(3, 2))
print(my_twos(1, 4))

[[2. 2.]
 [2. 2.]
 [2. 2.]]
[[2. 2. 2. 2.]]


In [17]:
# Question 8 
subtract = lambda x, y : x - y
print(subtract(8, 5))
print(subtract(3, -7))


3
10


In [18]:
# Question 9
def add_string(s1, s2):
    return s1 + s2

s1 = add_string("Programming", " ")
s2 = add_string("is ", "fun!")
add_string(s1, s2)

'Programming is fun!'

In [19]:
# Question 10
# def fun(a):
#     return 1

# print(fun())
# OUTPUT:
# TypeError: fun() missing 1 required positional argument: 'a'


In [20]:
# def nothing():
# return 0
# OUTPUT:
# IndentialError: expected an indented block

In [21]:
# Question 11
def greeting(name, age):
    out = "Hi, my name is " + name + \
        " and I am " + str(age) + " years old."
    return out

print(greeting("John", 26))
print(greeting("Kate", 19))

Hi, my name is John and I am 26 years old.
Hi, my name is Kate and I am 19 years old.


In [22]:
# Question 12
def my_donut_area(r1, r2):
    return np.pi * (r2 ** 2 - r1 ** 2)

print(my_donut_area(np.arange(1, 4), np.arange(2, 7, 2)))

[ 9.42477796 37.69911184 84.82300165]


In [23]:
# Question 13 
def my_within_tolerance(A, a, tol):
    out = []
    for i in A:
        if abs(i-a)<tol:
            out.append(i)
    return out

print(my_within_tolerance([0, 1, 2, 3], 1.5, 0.75))
print(my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03))



[1, 2]
[0.47000000000000003, 0.48, 0.49, 0.5, 0.51, 0.52]


In [24]:
# Question 14
def bounding_array(A, top, bottom):
    out = []
    for i in A:
        if i <= bottom:
            out.append(bottom)
        elif bottom < i < top:
            out.append(i)
        else:
            out.append(top)
    return out

bounding_array(np.arange(-5, 6, 1), 3, -3)

[-3, -3, -3, -2, -1, 0, 1, 2, 3, 3, 3]