In [29]:
import numpy as np
import math

In [30]:
# Question 1
def my_sum(lst):
    out = 0
    for i in lst:
        out += i
    return out

print(my_sum([1,2,3]))
print(my_sum(range(1,101)))

6
5050


In [31]:
# Question 2
def my_chebyshev_poly1(n,x):
    out = []
    def my_sum(n, k):
        if n == 0:
            return 1
        elif n == 1:
            return k
        else:
            return 2*k*my_sum(n-1,k)-my_sum(n-2,k)
    for i in x:
        out.append(my_sum(n,i))
    return out

x = [1, 2, 3, 4, 5]
print(my_chebyshev_poly1(0,x))
print(my_chebyshev_poly1(1,x))
print(my_chebyshev_poly1(3,x))

[1, 1, 1, 1, 1]
[1, 2, 3, 4, 5]
[1, 26, 99, 244, 485]


In [32]:
# Question 3
def my_ackermann(m,n):
    if m == 0:
        return n+1
    elif m > 0 and n == 0:
        return my_ackermann(m-1,1)
    elif m > 0 and n > 0:
        return my_ackermann(m-1,my_ackermann(m,n-1))
    
print(my_ackermann(1,1))
print(my_ackermann(1,2))
print(my_ackermann(2,3))
print(my_ackermann(3,3))
print(my_ackermann(3,4))

3
4
9
61
125


In [33]:
# Question 4
def my_n_choose_k(n,k):
    if k == n or k == 0: 
        return 1 
    elif k == 1:
        return n
    else:
        return my_n_choose_k(n-1,k-1) + my_n_choose_k(n-1,k)
    
print(my_n_choose_k(10,1))
print(my_n_choose_k(10,10))
print(my_n_choose_k(10,3))


10
1
120


In [34]:
# Question 5
def my_change(cost, paid):
    change = []
    change_currency = [100, 50, 20, 10, 5, 1, 0.25, 0.10, 0.05, 0.01]
    diff = paid - cost
    while diff > 0.01: 
        for i in change_currency:
            if diff >= i:
                change.append(i)
                diff -= i
                break
    return change

print(my_change(27.57, 100))

[50, 20, 1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01]


In [35]:
# Question 6
def my_golden_ratio(n):
    if n == 1:
        return 1
    else: 
        return 1 + 1/my_golden_ratio(n-1)
    
print(my_golden_ratio(10))
print((1+math.sqrt(5))/2)

1.6181818181818182
1.618033988749895


In [36]:
# Question 7
def my_gcd(a,b):
    if b == 0:
        return a
    else:
        return my_gcd(b,a%b)
    
print(my_gcd(10,4))
print(my_gcd(33,121))
print(my_gcd(18,1))

2
11
1


In [50]:
# Question 8
def my_pascal_row(m):
    if m == 1:
        return [1]
    out = [1]
    for i in range(1,m-1):
        lst = my_pascal_row(m-1)
        out.append(lst[i-1]+lst[i])
    out.append(1)
    return out

print(my_pascal_row(1))
print(my_pascal_row(2))
print(my_pascal_row(3))
print(my_pascal_row(4))
print(my_pascal_row(5))

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]


In [38]:
# Question 9
def my_spiral_ones(n):
    if n == 1:
        return np.array([[1]])
    elif n == 2:
        return np.array([[1,1],[0,1]])
    elif n == 3:
        return np.array([[1,1,1],[0,0,1],[0,1,1]])
    elif n == 4:
        return np.array([[1,1,1,1],[0,0,0,1],[0,1,0,1],[0,1,1,1]])
    
    out = np.zeros((n,n))
    out[0,:] = np.ones(n)
    out[:,-1] = np.ones(n)
    out[-1,1:] = np.ones(n-1)
    out[2:,1] = np.ones(n-2)
    out[2:-2, 2:-2] = my_spiral_ones(n-4) 
    return out

print(my_spiral_ones(2))
print(my_spiral_ones(8))
    

[[1 1]
 [0 1]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 1. 1. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
# Question 10
def my_spiral_ones_2(n):
    out = np.zeros((n,n))
    cor = 'bot_right'
    row_start = col_start = 0
    row_end = col_end = n

    while row_start < row_end and col_start < col_end:
        rows = row_end - row_start
        cols = col_end - col_start
        if cor == 'top_right':
            out[row_start:row_end, col_start:col_end] = np.zeros((rows, cols))
            cor = 'top_left'
            col_start += 1
            row_start += 1
        elif cor == 'top_left':            
            out[row_start:row_end, col_start:col_end] = np.ones((rows, cols))
            cor = 'bot_left'
            col_start += 1
            row_end -= 1
        elif cor == 'bot_left':            
            out[row_start:row_end, col_start:col_end] = np.zeros((rows, cols))
            cor = 'bot_right'
            col_end -= 1
            row_end -= 1
        elif cor == 'bot_right':            
            out[row_start:row_end, col_start:col_end] = np.ones((rows, cols))
            cor = 'top_right'
            col_end -= 1
            row_start += 1
    return out

print(my_spiral_ones_2(4))
print(my_spiral_ones_2(5))


[[1. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 1. 1. 1. 1.]]


In [40]:
def change_mat(m, n, dir):
        res = np.zeros((m,n))
        if dir == 'right':
            res[0,:] = np.ones(n)
            res[:,-1] = np.ones(m)
        else:
            res[:,0] = np.ones(m)
            res[-1,:] = np.ones(n)
        return res

def my_spiral_ones_3(n):    
    out = np.zeros((n,n))
    dir = 'right'
    row_start = col_start = 0
    row_end = col_end = n
    while row_start < row_end and col_start < col_end:
        out[row_start:row_end, col_start:col_end] = \
            change_mat(row_end - row_start, col_end - col_start, dir)
        col_start += 1
        col_end -= 1
        if dir == 'right':
            row_start += 2
            dir = 'left'
        else:
            row_end -= 2
            dir = 'right'
    return out

print(my_spiral_ones_3(6))
print(my_spiral_ones_3(3))

[[1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]]


In [43]:
# Question 12
# For more details check out: https://en.wikipedia.org/wiki/Tower_of_Hanoi#Binary_solution
def my_tower_hanoi(n):
    tower_1 = [i for i in range(n,0,-1)]
    tower_2 = []
    tower_3 = []
    towers = [tower_1, tower_2, tower_3]
    move = 1
    max = 2 ** n
    while move < max:
        temp1 = (move & move-1)%3
        temp2 = ((move | move-1)+1)%3
        disk = towers[temp1].pop()
        towers[temp2].append(disk)
        print(f'Move disk {disk} from tower {temp1+1} to tower {temp2+1}.')
        move += 1

my_tower_hanoi(3)



[[3, 2, 1], [], []]
Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 3 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 1.
Move disk 2 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 3.
[[], [], [3, 2, 1]]


In [42]:
# Question 14
def partition(lst, start, end):
    top = start - 1
    compare_element = lst[end]

    for i in range(start, end):
        if lst[i] <= compare_element:
            top += 1
            lst[i], lst[top] = lst[top], lst[i]
    
    lst[top+1], lst[end] = lst[end], lst[top+1]
    return top + 1

def my_quicksort(lst, l=0, h=None):
    if h == None:
        h = len(lst)-1
    size = h-l+1
    stack = [0] * size

    stack[0], stack[1] = l, h
    top = 1

    while top >= 0:
        h = stack[top]
        top -= 1
        l = stack[top]
        top -= 1

        p = partition(lst, l, h)

        if p-1 > l:
            top = top + 1
            stack[top] = l
            top = top + 1
            stack[top] = p - 1

        if p+1 < h:
            top = top + 1
            stack[top] = p + 1
            top = top + 1
            stack[top] = h
    
    return lst

print(my_quicksort([2, 1, 3, 5, 6, 3, 8, 10]))
    

[1, 2, 3, 3, 5, 6, 8, 10]
