In [1]:
import numpy as np
import math

### Question 1
#### Write down the characteristic equation for matrix A = $\begin{bmatrix}3 & 2 \\ 5 & 3\end{bmatrix}$

In [2]:
A = np.array([[3, 2], [5, 3]])
poly = np.polynomial.Polynomial.fromroots(np.linalg.eigvals(A))
poly

Polynomial([-1., -6.,  1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

In [3]:
def my_quad_solver(a,b,c):
    r = []
    disc = b**2 - 4*a*c
    if disc == 0:
        r += [-b / (2*a)]
    elif disc > 0:
        r += [(-b+math.sqrt(disc))/(2*a), (-b-math.sqrt(disc))/(2*a)]
    else:
        None
    return r


In [4]:
# Question 2
roots = my_quad_solver(1, -6, -1) #--> eigenvalues from characteristic polynomial
roots2 = np.linalg.eigvals(A)
# Both methods give the same eigenvalues upto 14 decimal places.
for i in range(2):
    print(round(roots[i], 14) == round(roots2[i],14))
    print(roots[i], roots2[i])

True
6.16227766016838 6.16227766016838
True
-0.16227766016837952 -0.16227766016837908


In [5]:
def normalize(x):
    x_n = x / x.max()
    return x_n

In [6]:
# First eigenvector
eigvec = []
x = np.ones((2,1))
for i in range(5):
    x = np.dot(A, x)
    x = normalize(x)

print(f'{x}')
eigvec.append(x)

[[0.63245553]
 [1.        ]]


In [7]:
# Second eigenvector
x = np.ones((2,1))
a_inv = np.linalg.inv(A)
for i in range(8):
    x = np.dot(a_inv, x)
    x = normalize(x)

print(f'{x}')
eigvec.append(x)

[[ 1.        ]
 [-1.58113883]]


In [8]:
# Question 3
# Checking if Av = cv, c - eigenvalue, v - eigenvector
for i in range(2):
    print(np.dot(A,eigvec[i]))
    print(roots[i]*eigvec[i])
# They are same upto 7 decimal places. 

[[3.89736659]
 [6.16227764]]
[[3.89736657]
 [6.16227766]]
[[-0.16227766]
 [ 0.25658351]]
[[-0.16227766]
 [ 0.25658351]]
